########################
@baseUrl = http://localhost:8080/odata/v4/ems
@me = viewer:

###
GET {{baseUrl}}/Employees
Authorization: Basic {{me}}
###
GET {{baseUrl}}/Departments
Authorization: Basic {{me}}
###
GET {{baseUrl}}/Roles
Authorization: Basic {{me}}
###


POST {{baseUrl}}/Employees
Authorization: Basic {{me}}
Content-Type: application/json

{
  "firstName": "Trinh",
  "lastName": "Huynh",
  "dateOfBirth": "2000-01-01",
  "gender": "Male",
  "email": "trinhhuynh@abvn.com",
  "hireDate": "2022-05-18",
  "role_ID": "a208203c-7386-411a-aa63-d6dbd5914c42",
  "department_ID": "69655986-18cc-47cc-aec0-9967607e0c4d"
}
###

